export const routes = {
    home: "/",
    login: "/auth/login",
    signup: "/auth/signup",
    forgot: "/auth/forgot-password",
    reset: "/auth/reset-password",
    dashboard: "/admin/dashboard",
    users: "/admin/users",
    posts: "/admin/posts",
    events: "/admin/events",
    communities: "/admin/communities",
    communityDetail: "/admin/communities/:id",
    poems: "/admin/poems",

    publications: "/publications",
    publication: "/publication",
    evenements: "/evenements",
    islam: "/islam",
    tijania: "/tijania",
    faydaTijania: "/faydaTijania",
    liwaoulham: "/liwaoulham",
    ecrits: "/avis-du-cheick",
    profile: "/profile",
};
